#application: theraart
#version: 1
runtime: python37
#api_version: 1gcloud auth application-default login

default_expiration: "0d 0h 0m 5s"

handlers:
#- url: /static/
#  static_dir: myapp/static
#  http_headers:
#    Access-Control-Allow-Origin: "*"

- url: /.*
  script: auto

entrypoint: gunicorn -b :$PORT wsgi:app

